---
title: "Hate Raids - Data Visualization"
format: html
---


## Load libraries
```{r}
if (!require("plotly")) install.packages("plotly")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("data.table")) install.packages("data.table")
if (!require("wesanderson")) install.packages("wesanderson")
if (!require("ggthemes")) install.packages("ggthemes")
if (!require("ggpubr")) install.packages("ggpubr")
if (!require("lubridate")) install.packages("lubridate")
if (!require("scales")) install.packages("scales")
```




```{r}
fig2 = filtered_tweets %>%
  mutate(date = date(created_at)) %>% 
  ggplot(aes(date, fill=set)) +
  geom_histogram(color="#333333",
                 binwidth = 1) +
  labs(x = "Date", y = "Number of Tweets") +
  scale_x_date(breaks=date_breaks("week"),
               labels=date_format("%b %d")) + 
  scale_fill_manual(values = wes_palette("Darjeeling1", n = 3),
                    name=NULL)
```





```{r}
fig2 = fig2 +
  theme_minimal() +
  theme(legend.position = "top",
        text = element_text(size = 24),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
  )
fig2
```



```{r}
ggplotly(fig2)
```


```{r}
fig3 = tweets_nrc %>%
  mutate(date = date(created_at)) %>% 
  group_by(date, set) %>%
  summarise(mean = mean(emo_score)) %>% 
  ggplot(aes(set,
           mean,
           fill = set)
       ) +
  geom_boxplot(colour = "#111111") +
  geom_jitter(aes(fill = set),
              alpha = 0.75,
             width = 0.25,
             ) +
  labs(x = "Tweet Set", y = "Average Sentiment Score") +
  theme_minimal()+
  theme(text = element_text(size = 24),
        legend.position = "none") +
  scale_fill_manual(values = wes_palette("Darjeeling1", n = 3)) +
  coord_flip()
fig3
```



```{r}
ggplotly(fig3)
```

```{r}
fig4 = tweets_nrc %>%
  mutate(date = date(created_at)) %>% 
  group_by(date, set) %>%
  summarise(mean = mean(eng_score)) %>% 
  ggplot(aes(set,
           mean,
           fill = set)
       ) +
  geom_boxplot(colour = "#111111") +
  geom_jitter(aes(fill = set),
              alpha = 0.75,
             width = 0.25,
             ) +
  labs(x = "Tweet Set", y = "Average Engagement Score") +
  theme_minimal()+
  theme(text = element_text(size = 24),
        legend.position = "none") +
  scale_fill_manual(values = wes_palette("Darjeeling1", n = 3)) +
  coord_flip()
fig4
```


```{r}
ggplotly(fig4)
```
