---
title: "Hate Raids - Analyses"
format: html
editor: visual
---

## Load libraries

```{r}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("data.table")) install.packages("data.table")
if (!require("syuzhet")) install.packages("syuzhet")
if (!require("rstatix")) install.packages("rstatix")
```

## Clean data

Filter out unnecessary noise in tweets and limit to text column

```{r}
#vr_work_y0_tweets = vr_work_y0_tweets %>%
#  mutate(period = "y0")
#vr_work_y1_tweets = vr_work_y1_tweets %>%
#  mutate(period = "y1")

url_regex <- "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"

tweets_text = filtered_tweets %>%
  mutate(text = str_remove_all(text, url_regex)) %>%
  select(text)

```

```{r}
tweets_text = tweets_text
tweets_text %>%
  select(text)
tweets_text$text = gsub('(?i)raid','!.!.!.!', tweets_text$text)
tweets_text %>%
  select(text)
```

```{r}
tweets_sv = as.vector(get_sentiment(tweets_text$text, method = "nrc"))

```

```{r}
tweets_sv_df = as.data.frame(tweets_sv)
```

```{r}
tweets_sen = cbind(filtered_tweets, tweets_sv_df) %>%
  rename (sent_value = tweets_sv)
```

## Score for Sentiment

```{r}
emotions_tweets = get_nrc_sentiment(tweets_sen$text)
emo_bar_tweets = colSums(emotions_tweets)
emo_sum_tweets = data.frame(count=emo_bar_tweets, 
                             emotion=names(emo_bar_tweets))
emo_sum_tweets$emotion = factor(emo_sum_tweets$emotion, 
                                 levels=emo_sum_tweets$emotion[order(emo_sum_tweets$count, decreasing = TRUE)])
```

```{r}
tweets_nrc = cbind(tweets_sen, emotions_tweets) %>%
  filter(conversation_id == tweet_id)

```

## Calculate Emotional Score

```{r}
tweets_nrc = tweets_nrc %>%
  mutate (emo_score = positive - negative)
tweets_nrc
  
```

```{r}
tweets_nrc %>%
  group_by (set) %>%
  summarise(mean = mean(emo_score))
```

## Analyse for emotional score

```{r}
tweets_nrc %>%
  t_test(emo_score ~ set, detailed = TRUE) %>%
  add_significance()

tweets_nrc %>%
  cohens_d(emo_score ~ set)
```

# Analyze for Engagement Score

```{r}
tweets_nrc = tweets_nrc %>%
  mutate (eng_score = reply_count + like_count + retweet_count + quote_count)
tweets_nrc
```

```{r}
tweets_nrc %>%
  t_test(eng_score ~ set, detailed = TRUE) %>%
  add_significance()

tweets_nrc %>%
  cohens_d(eng_score ~ set)
```
